<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia</groupId>
        <artifactId>chromia-parent</artifactId>
        <version>0.2.10</version>
    </parent>

    <groupId>net.postchain</groupId>
    <artifactId>postchain-clients</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>directory-chain</module>
        <module>ft4-rell</module>
        <module>postchain-client</module>
        <module>chromia-client</module>
        <module>ft4-client</module>
    </modules>

    <name>Postchain Clients</name>
    <description>Parent of postchain-client, chromia-client and ft4-client</description>

    <properties>
        <revision>dev</revision>
        <postchain.version>3.49.17</postchain.version>
        <directory.chain.version>1.110.5</directory.chain.version>
        <ft4.version>v1.2.0r</ft4.version>
        <rell.maven.plugin.version>1.2.3</rell.maven.plugin.version>
        <kotlin.version>2.3.0</kotlin.version>

        <maven.compiler.release>17</maven.compiler.release>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <kotlin.compiler.jvmTarget>17</kotlin.compiler.jvmTarget>

        <kotlin.code.style>obsolete</kotlin.code.style> <!-- Kotlin obsolete IntelliJ IDEA codestyle -->

        <!--suppress UnresolvedMavenProperty -->
        <directory.source>directory-chain/target/directory1/src</directory.source>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain</artifactId>
                <version>${postchain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>postchain-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>chromia-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>ft4-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>directory-chain</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>ft4-rell</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>

            <dependency>
              <groupId>org.wiremock</groupId>
              <artifactId>wiremock</artifactId>
              <version>3.13.2</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <pluginRepositories>
        <pluginRepository>
            <id>rellmaven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
        <pluginRepository>
            <id>kotlin-bcv-maven-plugin</id>
            <url>https://gitlab.com/api/v4/projects/64479054/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <snapshotRepository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </snapshotRepository>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </repository>
    </distributionManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <version>${kotlin.version}</version>
                    <executions>
                        <execution>
                            <id>compile</id>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                    <sourceDir>${project.basedir}/src/main/java</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                        <execution>
                            <id>test-compile</id>
                            <goals>
                                <goal>test-compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                                    <sourceDir>${project.basedir}/src/test/java</sourceDir>
                                    <sourceDir>${project.basedir}/target/generated-test-sources</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>net.postchain.rell</groupId>
                    <artifactId>rell-maven-plugin</artifactId>
                    <version>${rell.maven.plugin.version}</version>
                    <configuration>
                        <source>${maven.multiModuleProjectDirectory}/${directory.source}</source>
                        <postchainClientConfig>
                            <failover.attempts>2</failover.attempts>
                            <connect.timeout>10000</connect.timeout>
                        </postchainClientConfig>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <environmentVariables>
                            <D1_SOURCE>${maven.multiModuleProjectDirectory}/${directory.source}</D1_SOURCE>
                        </environmentVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <configuration>
                        <environmentVariables>
                            <D1_SOURCE>${maven.multiModuleProjectDirectory}/${directory.source}</D1_SOURCE>
                        </environmentVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.chromaway</groupId>
                    <artifactId>kotlin-bcv-maven-plugin</artifactId>
                    <version>0.2.0</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                    <executions>
                        <execution>
                            <id>check</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>animal-sniffer-maven-plugin</artifactId>
                <version>1.24</version>
                <configuration>
                    <signature>
                        <groupId>org.codehaus.mojo.signature</groupId>
                        <artifactId>java18</artifactId> <!-- Java 1.8 -->
                        <version>1.0</version>
                    </signature>
                </configuration>
                <executions>
                    <execution>
                        <id>check-java-api</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>chromia-parent</id>
            <name>Chromia parent GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/50818999/packages/maven</url>
        </repository>
        <repository>
            <id>postchain</id>
            <name>Postchain GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/32294340/packages/maven</url>
        </repository>
    </repositories>

    <profiles>
        <profile>
            <id>d1-local</id>
            <activation>
                <property>
                    <name>local</name>
                </property>
            </activation>
            <properties>
                <!--suppress UnresolvedMavenProperty -->
                <directory.source>../directory-chain/src</directory.source>
            </properties>
        </profile>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-plugin</artifactId>
                        <configuration>
                            <args>
                                <arg>-Werror</arg>
                            </args>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <licenses>
        <license>
            <name>Apache-2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
</project>
