<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia</groupId>
        <artifactId>chromia-parent</artifactId>
        <version>0.1.6</version>
    </parent>

    <groupId>net.postchain</groupId>
    <artifactId>postchain-clients</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>directory-chain</module>
        <module>postchain-client</module>
        <module>chromia-client</module>
        <module>coverage-report-aggregate</module>
    </modules>

    <name>Postchain Clients</name>
    <description>Parent of postchain-client and chromia-client</description>

    <properties>
        <revision>dev</revision>
        <postchain.version>3.28.1</postchain.version>
        <directory.chain.version>1.88.0</directory.chain.version>
        <rell.maven.plugin.version>0.14.0</rell.maven.plugin.version>
        <kotlin.version>2.0.0</kotlin.version>

        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <kotlin.compiler.jvmTarget>21</kotlin.compiler.jvmTarget>

        <kotlin.code.style>obsolete</kotlin.code.style> <!-- Kotlin obsolete IntelliJ IDEA codestyle -->

        <!--suppress UnresolvedMavenProperty -->
        <directory.source>directory-chain/target/directory1/src</directory.source>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain</artifactId>
                <version>${postchain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>postchain-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>chromia-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>directory-chain</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>

            <dependency>
              <groupId>org.wiremock</groupId>
              <artifactId>wiremock</artifactId>
              <version>3.12.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <pluginRepositories>
        <pluginRepository>
            <id>rellmaven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
        <pluginRepository>
            <id>kotlin-bcv-maven-plugin</id>
            <url>https://gitlab.com/api/v4/projects/64479054/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <snapshotRepository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </snapshotRepository>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </repository>
    </distributionManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <version>${kotlin.version}</version>
                    <executions>
                        <execution>
                            <id>compile</id>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                    <sourceDir>${project.basedir}/src/main/java</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                        <execution>
                            <id>test-compile</id>
                            <goals>
                                <goal>test-compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                                    <sourceDir>${project.basedir}/src/test/java</sourceDir>
                                    <sourceDir>${project.basedir}/target/generated-test-sources</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>net.postchain.rell</groupId>
                    <artifactId>rell-maven-plugin</artifactId>
                    <version>${rell.maven.plugin.version}</version>
                    <configuration>
                        <source>${maven.multiModuleProjectDirectory}/${directory.source}</source>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <environmentVariables>
                            <D1_SOURCE>${maven.multiModuleProjectDirectory}/${directory.source}</D1_SOURCE>
                        </environmentVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <configuration>
                        <environmentVariables>
                            <D1_SOURCE>${maven.multiModuleProjectDirectory}/${directory.source}</D1_SOURCE>
                        </environmentVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.chromaway</groupId>
                    <artifactId>kotlin-bcv-maven-plugin</artifactId>
                    <version>0.1.0</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                    <executions>
                        <execution>
                            <id>check</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>chromia-parent</id>
            <name>Chromia parent GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/50818999/packages/maven</url>
        </repository>
        <repository>
            <id>postchain</id>
            <name>Postchain GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/32294340/packages/maven</url>
        </repository>
    </repositories>

    <profiles>
        <profile>
            <id>d1-local</id>
            <activation>
                <property>
                    <name>local</name>
                </property>
            </activation>
            <properties>
                <!--suppress UnresolvedMavenProperty -->
                <directory.source>../directory-chain/src</directory.source>
            </properties>
        </profile>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-plugin</artifactId>
                        <configuration>
                            <args>
                                <arg>-Werror</arg>
                            </args>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.10</version>
                        <executions>
                            <execution>
                                <id>default-prepare-agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-prepare-agent-integration</id>
                                <goals>
                                    <goal>prepare-agent-integration</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-report</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-report-integration</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report-integration</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
