<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>postchain-clients</artifactId>
        <groupId>net.postchain</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <artifactId>directory-chain</artifactId>
    <name>Directory Chain</name>
    <description>Wrapper project for retrieving the directory chain rell code</description>

    <build>
        <plugins>
            <plugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-scm-plugin</artifactId>
                  <version>1.11.2</version>
                  <configuration>
                      <connectionUrl>scm:git:https://gitlab.com/chromaway/core/directory-chain.git</connectionUrl>
                      <scmVersion>${directory.chain.version}</scmVersion>
                      <scmVersionType>tag</scmVersionType>
                  </configuration>
                  <executions>
                      <execution>
                          <id>d1-resources-checkout</id>
                          <phase>generate-resources</phase>
                          <goals>
                              <goal>checkout</goal>
                          </goals>
                          <configuration>
                              <checkoutDirectory>${project.build.directory}/directory1</checkoutDirectory>
                              <skipCheckoutIfExists>true</skipCheckoutIfExists>
                          </configuration>
                      </execution>
                      <execution>
                          <id>d1-resources-update</id>
                          <phase>generate-resources</phase>
                          <goals>
                              <goal>update</goal>
                          </goals>
                          <configuration>
                              <workingDirectory>${project.build.directory}/directory1</workingDirectory>
                          </configuration>
                      </execution>
                  </executions>
            </plugin>
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>install-libs</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>rell-install</goal>
                        </goals>
                        <configuration>
                            <source>${project.build.directory}/directory1/src</source>
                            <configPath>${project.build.directory}/directory1/chromia.yml</configPath>
                            <target>${project.build.directory}/directory1</target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>d1-local</id>
            <activation>
                <property>
                    <name>local</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                      <artifactId>maven-scm-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>d1-resources-checkout</id>
                                <phase>none</phase>
                            </execution>
                            <execution>
                                <id>d1-resources-update</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>net.postchain.rell</groupId>
                        <artifactId>rell-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>install-libs</id>
                                <configuration>
                                    <source>${project.parent.basedir}/../directory-chain/src</source>
                                    <configPath>${project.parent.basedir}/../directory-chain/chromia.yml</configPath>
                                    <target>${project.parent.basedir}/../directory-chain</target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <repositories>
      <repository>
        <id>Directory Chain</id>
        <url>https://gitlab.com/api/v4/projects/46396847/packages/maven</url>
      </repository>
    </repositories>
</project>
